# Generated by Django 4.2.3 on 2023-07-23 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='requests',
            field=models.ManyToManyField(null=True, related_name='users', to='utils.request'),
        ),
    ]
