# Generated by Django 4.2.3 on 2023-07-23 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('word', '0001_initial'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Level',
        ),
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='content',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='word',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='word.word'),
        ),
    ]
